version: '3'
services:
  vote:
    image: 980104576357.dkr.ecr.us-east-1.amazonaws.com/vote:latest
    container_name: vote
    ports:
      - "5000:5000"
    restart: unless-stopped

  result:
    image: 980104576357.dkr.ecr.us-east-1.amazonaws.com/result:latest
    container_name: result
    ports:
      - "5001:5001"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
